# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-12 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('telefon', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
