# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-12 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20180212_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='telefon',
            new_name='tel',
        ),
        migrations.AddField(
            model_name='contact',
            name='is_appointed',
            field=models.BooleanField(default=False),
        ),
    ]
