# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180201_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
