# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20180201_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='color',
            field=models.CharField(default=1, max_length=7),
            preserve_default=False,
        ),
    ]
