# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
