# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20180201_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
    ]
