# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20180201_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='color',
        ),
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_allday',
        ),
        migrations.RemoveField(
            model_name='event',
            name='place',
        ),
    ]
