# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-02 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20180201_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='is_allday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
