# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-04 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20180204_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
