# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-05 13:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_event_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='owner',
        ),
    ]
