# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-07 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_auto_20180207_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='client',
        ),
    ]
