# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-07 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_remove_event_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_shown',
            field=models.BooleanField(default=False),
        ),
    ]
