# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-08 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_event_is_shown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_shown',
        ),
    ]
