# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 10:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20171121_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee_status',
            new_name='employee_state',
        ),
    ]
