# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20171122_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('E', 'Pracownik'), ('A', 'Administrator')], default='E', max_length=1),
        ),
    ]
