# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-20 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee',
            new_name='user',
        ),
    ]
