# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-25 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_auto_20180120_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_nr',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_state',
            field=models.CharField(choices=[('A', 'Aktywny'), ('U', 'Nieaktywny')], default='A', max_length=1),
        ),
    ]
