# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='surname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
