# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='pesel',
            field=models.DecimalField(decimal_places=0, default=90041414375, max_digits=11),
            preserve_default=False,
        ),
    ]
