# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_client_pesel'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_id',
            field=models.CharField(default=4161, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='client_status',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='doc_nr',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='doc_type',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
