# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 11:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0009_contactdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(max_length=1)),
                ('street', models.CharField(max_length=40)),
                ('apartment_nr', models.CharField(max_length=20)),
                ('post', models.CharField(max_length=40)),
                ('postal_code', models.CharField(max_length=6)),
                ('country', models.CharField(max_length=2)),
                ('house_nr', models.CharField(max_length=20)),
                ('valid_since_date', models.DateField()),
                ('valid_to_date', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientaddress_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientaddress_updated_by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='ContactData',
            new_name='ClientContactData',
        ),
    ]
