# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_auto_20171117_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaddress',
            name='valid_to_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
