# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 17:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0011_auto_20171117_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='client',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='clientaddress',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='clientaddress',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='clientcontactdata',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='clientcontactdata',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='client',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
