# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 20:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_auto_20171118_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientaddress',
            name='valid_since_date',
        ),
        migrations.RemoveField(
            model_name='clientaddress',
            name='valid_to_date',
        ),
    ]
