# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_auto_20171118_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientcontactdata',
            name='valid_since_date',
        ),
        migrations.RemoveField(
            model_name='clientcontactdata',
            name='valid_to_date',
        ),
    ]
