# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_auto_20171122_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_since', models.DateField()),
                ('valid_to', models.DateField()),
                ('nr', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=1)),
            ],
        ),
        migrations.RenameField(
            model_name='client',
            old_name='client_status',
            new_name='client_state',
        ),
        migrations.AddField(
            model_name='agreement',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client'),
        ),
    ]
