# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_auto_20171122_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agreement',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
