# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0018_auto_20171122_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreement',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='declaration',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='declaration',
            name='product_id',
        ),
        migrations.DeleteModel(
            name='Agreement',
        ),
        migrations.DeleteModel(
            name='Declaration',
        ),
    ]
