# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0019_auto_20171123_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='gender',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
