# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0020_client_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
