# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0021_auto_20171205_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcontactdata',
            name='state',
            field=models.CharField(choices=[('M', 'Adres zamieszkania'), ('Z', 'Adres zameldowania'), ('P', 'Adres korespondencyjny')], default='M', max_length=1),
        ),
    ]
