# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0022_clientcontactdata_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientcontactdata',
            name='state',
        ),
        migrations.AlterField(
            model_name='clientcontactdata',
            name='contact_type',
            field=models.CharField(choices=[('M', 'Adres zamieszkania'), ('Z', 'Adres zameldowania'), ('P', 'Adres korespondencyjny')], default='M', max_length=1),
        ),
    ]
