# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0023_auto_20171213_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaddress',
            name='contact_type',
            field=models.CharField(choices=[('M', 'Adres zamieszkania'), ('Z', 'Adres zameldowania'), ('P', 'Adres korespondencyjny')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='clientcontactdata',
            name='contact_type',
            field=models.CharField(max_length=1),
        ),
    ]
