# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0024_auto_20171213_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaddress',
            name='contact_type',
            field=models.CharField(max_length=1),
        ),
    ]
