# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 19:51
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0025_auto_20171213_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaddress',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
