# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0027_auto_20171215_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birthday',
            field=models.DateField(default='2017-12-21'),
        ),
        migrations.AlterField(
            model_name='clientaddress',
            name='contact_type',
            field=models.CharField(choices=[('R', 'Adres zameldowania'), ('A', 'Adres zamieszkania'), ('C', 'Adres kontaktowy')], default='R', max_length=1),
        ),
    ]
