# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0029_auto_20171225_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birthday',
            field=models.DateField(default='2017-12-27'),
        ),
    ]
