# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0030_auto_20171227_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birthday',
            field=models.DateField(default='2017-12-28'),
        ),
        migrations.AlterField(
            model_name='clientcontactdata',
            name='contact_type',
            field=models.CharField(choices=[('E', 'E-mail'), ('T', 'Numer telefonu')], default='E', max_length=1),
        ),
    ]
