# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-31 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0031_auto_20171228_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birthday',
            field=models.DateField(default='2017-12-31'),
        ),
    ]
