# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0032_auto_20171231_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birthday',
            field=models.DateField(default='2018-01-02'),
        ),
    ]
