# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-25 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0042_auto_20180123_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birthday',
            field=models.DateField(default='2018-01-25'),
        ),
    ]
