# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-02 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0044_auto_20180201_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birthday',
            field=models.DateField(default='2018-02-02'),
        ),
    ]
