# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-05 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0046_auto_20180204_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birthday',
            field=models.DateField(default='2018-02-05'),
        ),
    ]
