# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-12 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0049_auto_20180208_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birthday',
            field=models.DateField(default='2018-02-12'),
        ),
    ]
