# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='valid_since',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='valid_to',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
