# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='state',
            field=models.CharField(choices=[('A', 'Active'), ('U', 'Unactive')], default='A', max_length=1),
        ),
    ]
