# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-20 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0002_auto_20171127_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='state',
            field=models.CharField(choices=[('A', 'Aktywny'), ('U', 'Nieaktywny')], default='A', max_length=1),
        ),
    ]
