# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-20 10:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agreements', '0003_auto_20180120_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='buyer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
