# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-08 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_remove_notification_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_shown',
            field=models.BooleanField(default=False),
        ),
    ]
