# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-08 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_is_shown'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='owner',
            new_name='receiver',
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('B', 'Birthday'), ('E', 'Event'), ('R', 'Commision - request'), ('D', 'Commision - decision')], default=None, max_length=1),
        ),
    ]
