# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-08 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_auto_20180208_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='receiver',
            new_name='receivers',
        ),
    ]
