# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-12 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_auto_20180208_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.CharField(max_length=150),
        ),
    ]
