# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-12 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_auto_20180212_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('B', 'Birthday'), ('E', 'Event'), ('R', 'Commision - request'), ('D', 'Commision - decision'), ('M', 'Message')], default=None, max_length=1),
        ),
    ]
