# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 10:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20171122_0908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='status',
            new_name='state',
        ),
    ]
