# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 11:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20171122_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productparameter',
            name='slug',
        ),
    ]
