# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_productparameter_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='duration',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=2),
            preserve_default=False,
        ),
    ]
