# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productparameter',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='products.Product'),
        ),
    ]
