# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20171122_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productparameter',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
