# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20171122_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='duration',
        ),
        migrations.AddField(
            model_name='productparameter',
            name='duration',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=2),
            preserve_default=False,
        ),
    ]
