# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20171125_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productparameter',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
