# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-22 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20180122_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productparameter',
            name='product_type',
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_type', to='products.ProductType'),
            preserve_default=False,
        ),
    ]
