# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-23 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20180122_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.CharField(choices=[('A', 'Aktywny'), ('U', 'Nieaktywny')], default='U', max_length=1),
        ),
    ]
