# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-23 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20180123_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productparameter',
            old_name='value',
            new_name='val',
        ),
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.CharField(choices=[('A', 'Aktywny'), ('U', 'Nieaktywny')], default='A', max_length=1),
        ),
    ]
