# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-23 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20180123_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productparameter',
            old_name='val',
            new_name='value',
        ),
    ]
