# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-20 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20180123_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='productparameter',
            name='client_fee',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20),
            preserve_default=False,
        ),
    ]
