# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-20 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_productparameter_client_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productparameter',
            name='client_fee',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='productparameter',
            name='value',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
    ]
